README.md, docker-compose.yml, local/Dockerfile, local/channel-rust-dummy.toml, local/generate-gpg-key.conf, local/idle.sh, local/run.sh, local/secrets.toml, local/setup.sh, run.sh, src/main.rs
This PR adds all the tooling necessary to run a release locally without the need of production credentials. The goal is to be able to start a release by running these two commands in two separate terminals:
```
docker-compose up
./run.sh <channel>
```
=> Add support for running releases locally

.github/workflows/ci.yml, local/channel-rust-beta.toml, local/channel-rust-nightly.toml, local/channel-rust-stable.toml, local/run.sh, local/secrets.toml, run.sh, src/main.rs
This PR adds a CI pipeline to `promote-release`, which runs both the standard `cargo fmt`/`cargo clippy`/`cargo test` but also a local release for all the channels. Running CI currently takes around 16 minutes, as running local releases from scratch is slow.
The PR can be reviewed commit-by-commit.
=> Add CI to the repository

local/run.sh, src/config.rs, src/main.rs
When `promote-release` currently recompresses tarballs from `.xz` to `.gz`, it uses the best compression level (9), which on my machine takes ~90 seconds to run for the couple of tarballs downloaded during local builds. That's what we want for production, but it's a waste of time for local releases.
This PR adds an environment variable to change the compression level, and sets it to 1 when doing local builds. When the environment variable is missing the highest compression level (9) will be used.
This PR also centralizes parsing environment variables in a new `Config` struct and adds some utilities to make it more ergonomic to parse the environment. Since this is going to run inside a Docker container I'm planning to move all the existing configuration in `secrets.toml` over to …
=> Recompress tarballs faster on CI and local releases

local/run.sh, local/secrets.toml, src/config.rs, src/main.rs
This PR changes `promote-release` to load its configuration from environment variables, instead of a `secrets.toml` text file. This will make it easier to run the tool on AWS CodeBuild.
=> Load configuration from the environment

src/config.rs, src/main.rs
This PR implements the changes needed to prevent https://github.com/rust-lang/rustup/issues/2504 from happening again:
* The whole `/dist/*` directory is invalidated in CloudFront instead of the singe manifest file. This will slightly impact cache hits after a release happens, but it will also prevent the root cause of the outage.
* `promote-release` will now refuse to do multiple releases on the same channel on the same day, unless the `PROMOTE_RELEASE_ALLOW_MULTIPLE_TODAY` environment variable is set. I'm not sure we'll ever use the environment variable, but at least it's there if we actually need it.
I'll prepare a backport to the `promote-release` copy in RCS once this PR is merged.
The PR can be reviewed commit-by-commit.
=> Implement changes following Friday's outage

.github/workflows/ci.yml
We only need the artifact for the Docker image to transfer data between jobs, and there is no point in downloading it separately. This sets the retention period to the minimum amount available, one day.
=> Avoid wasting CI artifact storage space

src/main.rs
Mistakenly left this in, woops.
=> Remove debug line

src/main.rs
Once signatures are generated, the current release process reuploads everything to the `rust-lang-ci2` S3 bucket, but I can't see a reason why it's doing that or why we actually need that. Any reason we should keep this @Mark-Simulacrum?
=> Stop reuploading files to the artifacts S3 bucket

src/build_manifest.rs, src/config.rs, src/main.rs
Our releases currently include a bunch of "internal" files that are not useful for our downstream users but that happen to be stored in the artifacts bucket, such as CPU graphs, the `build-manifest` component, and similar. This PR implements purging them before shipping the release, by only retaining the files mentioned in the manifest, the files generated by `build-manifest` or the files matching a pattern explicitly allowed by `promote-release`.
This feature only works on rustc branches that include https://github.com/rust-lang/rust/pull/78196, and is currently **disabled**. To enable it the `PROMOTE_RELEASE_WIP_PRUNE_UNUSED_FILES` environment variable needs to be set. My current plan is to merge this, run a dev release with this feature enable, compare the result with the prod release, …
=> [disabled] Remove unused files from the release

src/main.rs
This PR follows up on https://github.com/rust-lang/promote-release/issues/23 implementing support for https://github.com/rust-lang/rust/pull/78486. Now that all the files we're shipping are included in the manifest we can avoid having a list of allowed patterns.
=> Stop having an explicit list of allowed file names for pruning

local/run.sh, src/config.rs, src/main.rs
This commit adds the `PROMOTE_RELEASE_BYPASS_STARTUP_CHECKS` enviornment variable, which replaces the `PROMOTE_RELEASE_ALLOW_MULTIPLE_TODAY` environment variable and adds more uses to it. Namely, the new enviornment variable will allow to skip all the startup checks that are meant to prevent an unwanted release from happening, not just the one that prevents multiple releases in the same day.
The use for this will mainly be to re-run dev stable releases. Instead of running a script to invalidate the current dev stable release and then starting the release process, it will be possible to just run:
```
./start-release.py dev stable --bypass-startup-checks
```
=> Add the PROMOTE_RELEASE_BYPASS_STARTUP_CHECKS variable

prod/Dockerfile, src/smoke_test.rs
If we don't use the minimal profile, releases will fail if an optional component in the default profile goes missing. This is what caused today's nightly outage.
=> Make sure to use the minimal rustup profile during smoke tests

Cargo.lock, Cargo.toml, src/build_manifest.rs, src/config.rs, src/main.rs
This PR adds two environment variables to `promote-release`:
* `PROMOTE_RELEASE_NUM_THREADS`: while looking at the CPU graphs for our builds, I noticed the CPU was not maxed out during the parallel parts of the release process. The variable will allow to test different amounts of parallelism to see which one performs better.
* `PROMOTE_RELEASE_WIP_RECOMPRESS:` I want to see how much longer the release process will take to recompress all the `.xz` into `.gz`, so this PR adds a temporary environment variable I can set when testing a build.
=> Add WIP variable to test recompression

local/run.sh
Rust 1.48.0 is the first release to include my changes that simplified downloading stable artifacts, namely `src/version` and using the same version number in dist tarballs. This PR removes that legacy code and fixes CI, which is currently stuck trying to download `cargo-0.49.0` instead of `cargo-1.48.0`.
=> Remove legacy hacks to download stable artifacts during local releases

local/run.sh, src/config.rs, src/main.rs, src/sign.rs
This should automatically put artifacts in cold storage as they decrease in use
over time. We do this for all artifacts, including documentation. Many of the
files uploaded for documentation aren't going to actually be eligible for colder
storage (there's a minimum size of 128KB) but in that case they'll just be
stored in standard storage as before and not monitored, which works well for us.
r? @pietroalbini
=> Switch dist artifact uploads to intelligent tiering

src/config.rs, src/curl_helper.rs, src/discourse.rs, src/github.rs, src/main.rs
Tested locally -- see https://internals.rust-lang.org/t/rust-1-62-0-pre-release-testing-v2/16983 (may need admin credentials) and https://github.com/Mark-Simulacrum/blog.rust-lang.org/pull/8 for the sample PRs opened by this.
I think the PR being opened vs. directly pushing makes sense, but we could consider altering that in the future, once this is proven to work.
=> Post internals + blog PR after publishing dev-static releases

src/branching.rs, src/config.rs, src/curl_helper.rs, src/discourse.rs, src/github.rs, src/main.rs
This bumps branches on rust-lang/rust and creates the cargo branch at the
appropriate commit; the only missing component is the actual PR that will bump
the channel (src/ci/channel) to stable and cherry pick a fresh copy of the
release notes. I think it makes sense for now to leave that step to human hands:
it's pretty manual (need to track down the release notes, which might or might
not have merged already; need to check for last minute beta backports...). So
humans likely are involved anyway, at which point it's not really a huge win for
us to automate opening a PR or creating a temporary branch.
This automation already avoids the annoying bits and the bits that require
privileges (e.g., force pushing branches).
Based on #45
=> Support branch promotion

.github/workflows/ci.yml, src/branching.rs, src/github.rs
GitHub doesn't return merge commits when searching by changed file path,
so our previous logic was finding the human-authored commit rather than
the bors merge commit. New logic looks for the first bors commit which
has the last human commit changing src/version, which should hopefully
work here.
Fixes #49
=> Fix src/version parent finding

src/config.rs
I noticed this in https://github.com/rust-lang/blog.rust-lang.org/pull/1087.
You can find the documentation of `%-?` in https://docs.rs/chrono/0.4.23/chrono/format/strftime/index.html#specifiers.
```rust
fn main() {
let scheduled_release_date = chrono::NaiveDate::from_ymd_opt(2023, 3, 9).unwrap();
println!("{}", scheduled_release_date.format("%B %d"));
println!("{}", scheduled_release_date.format("%B %-d"));
}
```
```console
March 09
March 9
```
=> Suppress zero padding in "scheduled for" date

src/build_manifest.rs, src/github.rs, src/main.rs
The blog repository has been configured to allow direct pushes (bypassing the regular branch protection), though not force pushes, by the promote release bot.
This hasn't been tested yet -- I figure the easiest thing is to do so as part of a release. Worst case we manually produce and merge the file, which isn't that hard.
=> Directly push dev-static announcement

.github/workflows/ci.yml
I think these are mostly no-op bumps, just using a newer NodeJS (16 vs 12) in their own dependencies. Not quite sure why that merits a major version, but seems like we should be on latest regardless.
=> Bump versions for action dependencies

local/run.sh, src/config.rs, src/main.rs
This adds support for recompressing the .xz tarballs in promote-release, with a goal of moving rust-lang/rust CI back to producing "balanced" profile binaries rather than the highly compressed ones currently produced. This will cut rust-lang/rust CI times while keeping the production artifacts in static.r-l.o equivalently compressed. The settings in this PR match the current configuration in rust-lang/rust's best compression profile.
This PR doesn't enable the .xz recompression by default, but that will happen in production as I've deployed the env variable with =1 already (we can remove that if we run into trouble in production easily). Depending on the impact to (especially) stable build times we may wish to bump the promote-release production container from 8 cores to 72 cores (the …
=> Recompress xz -> xz with tuned compression options

src/main.rs, src/recompress.rs
Best reviewed by-commit.
This has two changes:
* We decompress data just once before compressing into gzip and the optimized xz routine. This should broadly just be more efficient.
* Sort the list of files to recompress by length. Hopefully produces the desired tail-trimming on the parallel compression, but as the comments note it may be the case that we need our own threadpool or spawn_fifo from Rayon for that to actually work.
r? @pietroalbini
=> Refactor compression

local/Dockerfile, prod/Dockerfile
Haven't tested this locally, but seems like it might be a win. It's not really clear how much bandwidth CodeBuild machines _should_ have, and we don't today log how much bandwidth we actually end up using for the uploads.
I suspect we may want a Rust-based impl that can give us more insight into the upload metrics if we end up optimizing this further. S3 operations are roughly ~12/60 minutes for a build today, so not entirely trivial, but not very long either.
=> Parallelize S3 upload/download more

src/recompress.rs
Based on production data it seems likely that our previous attempt to schedule small files *last* rather than first didn't work out. This replaces the rayon-based parallelism for this loop with a custom, trivial scheduler, giving us direct control over how we schedule tasks.
This is completion slot on X axis (i.e., line number of the finished lines) vs. the duration in seconds reported for xz compression on the Y axis: 
It's not a perfect balance but it seems pretty likely that we're doing small files first rather than last.
I _think_ it might be possible to accomplish this with rayon by flipping the sort order -- but I think this is pretty simple as-is and to some extent is much clearer than trying to sort just right to match rayon's relatively undocumented behavior.
Review with …
=> Replace rayon with manual parallelism

Cargo.lock, prod/Dockerfile
I'm seeing consistent failures when trying a dev-static build:
> upload failed: release/dl/cargo-nightly-aarch64-unknown-linux-musl.tar.xz to s3://dev-static-rust-lang-org/dist/2023-05-07/cargo-nightly-aarch64-unknown-linux-musl.tar.xz SSL validation failed for https://dev-static-rust-lang-org.s3.us-west-1.amazonaws.com/dist/2023-05-07/cargo-nightly-aarch64-unknown-linux-musl.tar.xz TLS/SSL connection has been closed (EOF) (_ssl.c:997)
My suspicion is that we're hitting some kind of concurrency limit, so trying to reduce that.
=> Lower concurrency

src/config.rs, src/fastly.rs, src/main.rs
We are working on serving Rust releases through Fastly as well as CloudFront. The logic to invalidate cached released has therefore been slightly reworked to handle both CDNs.
First, new environment variables have been added to configure the Fastly integration. An API token is required as is the domain name that should get invalidated.
Second, a temporary environment variable has been added that enables the integration. This enables us to test the integration in the dev environment without requiring any changes to the production environment.
=> Invalidate release distribution on Fastly

src/fastly.rs
For better observability, a log statement is now emitted when Fastly's cache is purged.
=> Log request to purge Fastly cache

src/config.rs, src/fastly.rs, src/main.rs
Fastly does not support wildcard invalidations through its URL-based API, and also does not support invalidating a path prefix like `/dist/`. We are therefore switching to surrogate keys. Requests that match the path `^\/dist\/` get tagged with the surrogate key `/dist/*`, which is then used when invalidating the cache after a release.
The tagging implementation can be found in rust-lang/simpleinfra#295.
=> Invalidate the cache on Fastly using surrogate keys

src/fastly.rs
In the original implementation, we simply used the path for invalidations as the surrogate key. This worked fine when using the user interface to invalidate the cache, but broke when trying to use Fastly's API to do the same. While it is possible that we simply needed to URL-encode the key, a safer implementation is to avoid the problem in the first place by restricting the key to alphanumeric characters.
=> Simplify the surrogate key for Fastly

Cargo.lock, src/github.rs
Hopefully this gives us more information to fix the error we're hitting in Cargo tagging:
```
2023-08-24T13:46:49.982000+00:00 f9ef8b2d-88f0-4f4d-9ba2-55bbf2b79c28 Error: {"message":"Could not verify tag name","documentation_url":"https://docs.github.com/rest/git/tags#create-a-tag-object"}
2023-08-24T13:46:49.982000+00:00 f9ef8b2d-88f0-4f4d-9ba2-55bbf2b79c28
2023-08-24T13:46:49.982000+00:00 f9ef8b2d-88f0-4f4d-9ba2-55bbf2b79c28 Caused by:
2023-08-24T13:46:49.982000+00:00 f9ef8b2d-88f0-4f4d-9ba2-55bbf2b79c28 missing field sha at line 1 column 119
2023-08-24T13:46:49.982000+00:00 f9ef8b2d-88f0-4f4d-9ba2-55bbf2b79c28
```
=> Add additional logging for tag requests

src/main.rs
This modifies the code to correctly load the split cargo version into "current_cargo_version" and the split rustc version. This should fix our Cargo tagging support.
=> Fix Cargo tagging & version parsing

src/main.rs
This is likely to be very verbose, but hopefully will eventually give us request IDs for #77 which we can ask about to S3, or give us enough information to fix it locally. This has broken 2 nightlies in 12 days, which is a pretty high incidence rate so far.
=> Debug logging during s3 operations

src/main.rs
This reverts commit 075a92758d33eca17dfc2adef97f0673d5cd5965.
No issues seen since this was added, and it's *very* verbose. We've collected ~10 GB in the log group for releases as a result and it makes manually inspecting release logs more painful (e.g., during a release cycle).
My hope is that maybe the issue has gone away. Even if not, it seems plausible that the logging is sufficiently verbose it's hiding the issue due to changing how quickly things happen...
=> Revert "Debug logging during s3 operations"

src/config.rs
Now that https://dev-doc.rust-lang.org/1.76.0/releases.html exists, we can use it and not have to worry about https://github.com/rust-lang/rust/issues/101714 any more.
This is a follow-up for https://github.com/rust-lang/rust/pull/117888
=> Use internally-generated release notes for IRLO announcement

src/main.rs
After https://github.com/rust-lang/rust/pull/123246, the docs archived have files with a modification time from 2006. This meant that `s3 sync` wouldn't upload them. This PR modifies our extraction logic to always set the modification time to the current date.
=> Fix synchronization of docs

prod/Dockerfile
This PR installs the latest version of AWS CLI directly from AWS, since 22.04 installs v1 and 24.04 doesn't package it at all. We need a recent version because #89 uses the recent `--if-none-match` flag.
While I was at it I also bumped the container to Ubuntu 24.04.
=> Install recent AWS CLI in docker and update to Ubuntu 24.04

src/main.rs
This PR contains multiple fixes to #89:
* It now uses `--if-match` instead of `--if-none-match` when the file exists already, as noted in https://github.com/rust-lang/promote-release/pull/89#discussion_r2181330756
* It adds new manifests at the bottom of the file rather than at the top
* It handles releases with multiple manifests (for example, one for `beta` and one for `1.89-beta` in the case of beta releases)
I managed to test them locally and everything seems to work fine.
=> Followup fixes to `manifests.txt`

src/main.rs
This ensures that the file is *really* up to date.
=> Invalidate manifests.txt after updating it
